### ISSUE TITLE
"Are you alone?" Project CheckList

### ISSUE THREAD

**Issue by seungjjun** [seungjjun/are-you-alone#1]
### 월요일
- [x] 창 상단에 메인, 풋살 매치, 농구 매치, 같이해요 버튼 만들기
- [x] 각 버튼을 눌렀을 때 게시글을 조회할 수 있는 기능 구현하기
- [x] 메인 페이지 제외 각 페이지에 게시글을 작성할 수 있는 버튼과 페이지 만들기
- [x] 글 작성 페이지에서 글 작성 버튼을 눌렀을 때 글 목록에 글의 제목만 올라가는 기능 만들기 

### 화요일
- [x] 각 페이지의 게시글을 클릭했을 시 상세페이지가 보이는 기능 구현하기
- [x] 상세페이지 안에 게시글을 수정, 삭제 버튼 생성
- [x]  작성한 본문 내용을 상세 페이지에서 볼 수 있도록 구현하기
- [x] 수정하기 버튼을 눌렀을 때 게시글을 수정할 수 있는 기능 구현하기
- [x] 삭제하기 버튼을 눌렀을 때 게시글을 삭제할 수 있는 기능 구현하기

### 수요일
- [x] 풋살 매치 버튼을 눌렀을 때 풋살 팀원 모집 관련글만 조회할 수 있는 기능 구현하기
- [x] 농구 매치 버튼을 눌렀을 때 농구 팀원 모집 관련글만 조회할 수 있는 기능 구현하기
- [x] 같이해요 버튼을 눌렀을 때 풋살, 농구 외 스포츠 종목이나 게임 등 다른 것들도 같이 할 사람을 모집하는 글만 조회할 수 있는 기능 구현하기

### 목요일
- [ ] 메인페이지 하단에 모든 게시글을 조회할 수 있는 부분 만들기
- [ ] 풋살 매치, 농구 매치 페이지에서 지역선택, 레벨선택, 성별선택 버튼 만들기
- [ ] 각 버튼을 눌렀을 시 그 조건에 맞는 게시글만 보이게 하는 기능 구현하기

**Comment by bbhye1** [comment]
오늘 하루 완성된 형태로 배포하기 위한 목표를 설정하고 그걸 달성하기 위한 하위 단계목표를 세워주세요.
지금 작성하신 내용으로는 무엇이 완성되는지 알기 어렵습니다.
